- Tests/TestSuite/API.Tests/API.Tests.csproj
- Tests/TestSuite/API.Tests/UnitTest1.cs
- Tests/TestSuite/MVC.Tests/MVC.Tests.csproj
- Tests/TestSuite/MVC.Tests/UnitTest1.cs
- Tests/TestSuite/TestSuite.sln
Created a test folder with solutions for API and MVC testing
> Add test projects for API and MVC solutions

- Tests/TestSuite/API.Tests/CommodityTests.cs
- Tests/TestSuite/API.Tests/User.cs
- Tests/TestSuite/API.Tests/UsersTests.cs
Removed UnitTest.cs
Added commodityTest.cs and usersTest.cs
> Removed uneccessary file and added files to test endpoints

- CommodityTradingAPI/CommodityTradingAPI/CommodityTradingAPI.csproj
- CommodityTradingAPI/CommodityTradingAPI/Program.cs
- CommodityTradingAPI/CommodityTradingAPITests/CommodityTradingAPITests.csproj
Added some jwt bearer details in the program. I still need to create an authentication controller, but I need the db context
> Adding jwt authentication in program

- Database/Schema.sql
> Merge schema with fixed foreign key constraints to be consistent with GUID

- CommodityTradingApp/CommodityTradingApp/CommodityTradingApp.csproj.user
- CommodityTradingApp/CommodityTradingApp/Controllers/TraderController.cs
- CommodityTradingApp/CommodityTradingApp/Models/Trader.cs
- CommodityTradingApp/CommodityTradingApp/Views/Trader/Index.cshtml
Implemented a Trader Model, controller, and view. Thus far, an index of all available users will show up if manager, and only user's profile details will show up if not manager
> Mvc trader profile view

- CommodityTradingAPI/CommodityTradingAPI/CommodityTradingAPI.csproj
- CommodityTradingAPI/CommodityTradingAPI/CommodityTradingAPI.csproj.user
- CommodityTradingAPI/CommodityTradingAPI/Controllers/AuthenticationController.cs
- CommodityTradingAPI/CommodityTradingAPI/Program.cs
Jwt token should be created on a successful login, and this will be stored in a cookie. Once the dbcontext and models are merged, I can test if this actually works.
> Completed Jwt authentication and authentication controller

- CommodityTradingApp/CommodityTradingApp/Controllers/TradeController.cs
- CommodityTradingApp/CommodityTradingApp/Views/Trade/ActiveTrades.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/Trade/Index.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/Trade/TradeHistory.cshtml
https://localhost:7131/Trade/ActiveTrades to view trades that are open
> View active trades

- CommodityTradingAPI/CommodityTradingAPI/CommodityTradingAPI.csproj
- CommodityTradingAPI/CommodityTradingAPI/Controllers/AuthenticationController.cs
- CommodityTradingAPI/CommodityTradingAPI/Data/CommoditiesDbContext.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/LoginRequest.cs
- CommodityTradingAPI/CommodityTradingAPI/Program.cs
- Created a login DTO model
- Seeded users table with an admin user
- Users can login using the login endpoint
- Logout endpoint will remove the cookie
- Injected dbcontext into program.cs
- Fixed spelling errors in dbcontext
> Seeded users table with admin user

- CommodityTradingAPI/CommodityTradingAPITests/UnitTest1.cs
These tests are provisional but a scaffholding
> Merging basic tests written

- CommodityTradingApp/CommodityTradingApp/Controllers/CommoditiesController.cs
- CommodityTradingApp/CommodityTradingApp/Controllers/CommodityController.cs
- CommodityTradingApp/CommodityTradingApp/Controllers/TradeController.cs
- CommodityTradingApp/CommodityTradingApp/Controllers/TraderController.cs
- CommodityTradingApp/CommodityTradingApp/Models/Commodity.cs
- CommodityTradingApp/CommodityTradingApp/Program.cs
- CommodityTradingApp/CommodityTradingApp/Views/Commodity/Index.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/Shared/_Layout.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/Trade/ActiveTrades.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/Trade/CreateTrade.cshtml
-added drop down for trade options and moved the commodity boxes to 'trade now'
> Add commodities view

- CommodityTradingApp/CommodityTradingApp/Controllers/CommodityController.cs
- CommodityTradingApp/CommodityTradingApp/Controllers/TradeController.cs
- CommodityTradingApp/CommodityTradingApp/Models/Commodity.cs
- CommodityTradingApp/CommodityTradingApp/Views/Commodity/Index.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/Home/Index.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/Shared/_Layout.cshtml
- added comments of where api routes will be called
- sorted out homepage
> cleanup mvc

- CommodityTradingAPI/CommodityTradingAPI/CommodityTradingAPI.csproj
- CommodityTradingAPI/CommodityTradingAPI/Controllers/UserController.cs
- CommodityTradingAPI/CommodityTradingAPI/Services/AuditLogService.cs
- CommodityTradingAPI/CommodityTradingAPI/Services/ILog.cs
- CommodityTradingAPI/CommodityTradingAPI/Services/ILogger.cs
- CommodityTradingAPI/CommodityTradingAPITests/CommodityTradingAPITests.csproj
- CommodityTradingAPI/CommodityTradingAPITests/UnitTest1.cs
Adds
-Audit log service
-Audit log Class
-Blob storage client
-Folders for each days with logs titled based on time of change.
-Also created blob storage on azure
> Created auditLogService

- CommodityTradingAPI/CommodityTradingAPI/Controllers/AuthenticationController.cs
- CommodityTradingAPI/CommodityTradingAPI/Controllers/OrdersController.cs
- CommodityTradingAPI/CommodityTradingAPI/Controllers/TraderController.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/DTOs/CreateTradeDto.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/DTOs/LoginRequest.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/ExternalCommodity.cs
- CommodityTradingAPI/CommodityTradingAPI/Service/ExternalApiService.cs
- CommodityTradingAPI/CommodityTradingAPITests/UnitTest1.cs
Orders controller
Created a httpclient service which connects to the external api
> Completed Orders controller

- CommodityTradingAPI/CommodityTradingAPI/Controllers/TraderController.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/DTOs/TraderAccountPortfolioDto.cs
- Created a dto for the account portfolio endpoint
- Completed trader account controller
> trader Account controller 

- CommodityTradingAPI/CommodityTradingAPI/Controllers/AuthenticationController.cs
- CommodityTradingAPI/CommodityTradingAPI/Program.cs
- CommodityTradingApp/CommodityTradingApp/CommodityTradingApp.csproj
- CommodityTradingApp/CommodityTradingApp/Controllers/LoginController.cs
- CommodityTradingApp/CommodityTradingApp/Models/Country.cs
- CommodityTradingApp/CommodityTradingApp/Models/Role.cs
- CommodityTradingApp/CommodityTradingApp/Models/RoleAssignment.cs
- CommodityTradingApp/CommodityTradingApp/Models/TraderAccount.cs
- CommodityTradingApp/CommodityTradingApp/Models/User.cs
- CommodityTradingApp/CommodityTradingApp/Program.cs
- CommodityTradingApp/CommodityTradingApp/Views/Login/Login.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/Shared/_Layout.cshtml
- CommodityTradingApp/CommodityTradingAppTests/CommodityTradingAppTests.csproj
- moved auth stuff to mvc
- login logout dissappears based on auth status
> Login mvc wire api

- CommodityTradingApp/CommodityTradingApp/CommodityTradingApp.csproj
- CommodityTradingApp/CommodityTradingApp/Controllers/UserController.cs
- CommodityTradingApp/CommodityTradingApp/Models/User.cs
- CommodityTradingApp/CommodityTradingApp/Models/ViewModel.cs
- CommodityTradingApp/CommodityTradingApp/Views/Login/Login.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/User/Create.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/User/Delete.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/User/Details.cshtml
- CommodityTradingApp/CommodityTradingApp/Views/User/Edit.cshtml
- CommodityTradingApp/CommodityTradingAppTests/CommodityTradingAppTests.csproj
Added all endpoints for User, including its model, controller, and view.
> User MVC final

- CommodityTradingAPI/CommodityTradingAPI/Controllers/CommodityController.cs
- CommodityTradingAPI/CommodityTradingAPI/Controllers/UserController.cs
- CommodityTradingAPI/CommodityTradingAPI/Program.cs
- CommodityTradingApp/CommodityTradingApp/CommodityTradingApp.csproj
- CommodityTradingApp/CommodityTradingApp/Controllers/CommodityController.cs
- CommodityTradingApp/CommodityTradingAppTests/CommodityTradingAppTests.csproj
Frontend can talk to the backend, so we can work on getting a trade made!!!
> initial wire up working

- Database/Seed.sql
Adds
- Seeding for commodities (currently only gold)
- A super user that has every role
> updated seed with superuser

- CommodityTradingAPI/CommodityTradingAPI/.editorconfig
- CommodityTradingAPI/CommodityTradingAPI/CommodityTradingAPI.csproj
- CommodityTradingAPI/CommodityTradingAPI/Controllers/CountryController.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/Country.cs
> Countries list controller

- CommodityTradingAPI/CommodityTradingAPI/Controllers/OrdersController.cs
- CommodityTradingAPI/CommodityTradingAPI/Controllers/TradeController.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/DTOs/CreateTradeDto.cs
- CommodityTradingAPI/CommodityTradingAPI/Program.cs
- CommodityTradingAPI/CommodityTradingAPI/Services/ExternalApiService.cs
Trades can be made, please review and smile while doing so
> create a trade

- CommodityTradingAPI/CommodityTradingAPI/Controllers/AuthenticationController.cs
- CommodityTradingAPI/CommodityTradingAPI/Program.cs
- CommodityTradingApp/CommodityTradingApp/CommodityTradingApp.csproj
- CommodityTradingApp/CommodityTradingApp/Controllers/LoginController.cs
- CommodityTradingApp/CommodityTradingApp/Program.cs
- CommodityTradingApp/CommodityTradingAppTests/CommodityTradingAppTests.csproj
- Routes can be authorised. I havent added the authorized header to any routes because I'm not sure which routes need authorisation.
- Seeded roles table with "Manager" and "Trader" roles.
- Admin user is seeded with the role of Manager.
- I did download older versions of a few packages to make this work so I'm not sure if this will cause issues down the line...
- Users controller needs to be changed so that users can be assigned roles when being created.
> Role based authorization working

- CommodityTradingAPI/CommodityTradingAPI/Controllers/UserController.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/CreateUser.cs
just needs to be done on the front end now
> User controller adds a role on api side

- CommodityTradingAPI/CommodityTradingAPI/Controllers/UserController.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/CreateUser.cs
Reverts anisahhoque/commodity-trading-app#40
see comment on last pull request
> Revert "User controller adds a role on api side"

- CommodityTradingAPI/CommodityTradingAPI/Controllers/UserController.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/CreateUser.cs
> reverted changes... my brain isnt working

- CommodityTradingAPI/CommodityTradingAPI/Controllers/RoleController.cs
- CommodityTradingAPI/CommodityTradingAPI/Models/User.cs
> quick comment added to make prtrade 

- CommodityTradingAPI/CommodityTradingAPI/Controllers/TradeController.cs
> gets all trades by trader id in the api

- CommodityTradingAPI/CommodityTradingAPI/Controllers/TradeController.cs
- CommodityTradingAPI/CommodityTradingAPI/Controllers/UserController.cs
- CommodityTradingAPI/CommodityTradingAPI/Services/AuditLogService.cs
- CommodityTradingAPI/CommodityTradingAPI/Services/ILogger.cs
- Made new function for logging in the service reducing lines of code
- Wrote full logs for trade and user controllers
> Completed audit logs for User and Trade Controller

- CommodityTradingApp/CommodityTradingApp/Controllers/TradeController.cs
> api bug fix (not perfect)

- CommodityTradingAPI/CommodityTradingAPI/Controllers/TraderController.cs
- CommodityTradingApp/CommodityTradingApp/Controllers/LoginController.cs
- CommodityTradingApp/CommodityTradingApp/Controllers/TraderController.cs
- CommodityTradingApp/CommodityTradingApp/Program.cs
Login bug removed - wont give a random success message when not logged in.
If user is not a manager, they will only see their own trader accounts.
jwtjwtjwt.
> protecting trader accoutns

- CommodityTradingApp/CommodityTradingApp/Controllers/CommodityController.cs
> gold chart gets latest data

- CommodityTradingAPI/CommodityTradingAPI/Controllers/UserController.cs
- CommodityTradingApp/CommodityTradingApp/Views/User/Details.cshtml
- can now view trader accounts in a more suitable fashion in the user details page
- shows a list of available trader accounts and links you to the trader details page
> trader account display in user details page
